services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M  # Limit frontend container to 512MB

  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/devopsdb
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 512M  # Limit backend container to 512MB

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ["--wiredTigerCacheSizeGB", "0.5"]
    deploy:
      resources:
        limits:
          memory: 1G  # Limit MongoDB to 1GB

volumes:
  mongo-data:
