apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: devops-sample-backend  # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 5000   # The port that the service will expose internally
      targetPort: 5000  # The port your backend application listens to inside the container
