apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: devops-sample-app-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-sample-app-frontend  # ✅ Ensure this matches the template
  template:
    metadata:
      labels:
        app: devops-sample-app-frontend  # ✅ This must match `matchLabels`
    spec:
      containers:
        - name: devops-sample-app-frontend
          image: mukeshsaini7/devops-sample-app-frontend:latest
          imagePullPolicy: Always  # ✅ Ensures it always pulls the latest image
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
