apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
data:
  mongo-init.js: |
    db = db.getSiblingDB("devopsdb");
    db.createUser({
      user: "admin",
      pwd: "password",
      roles: [{ role: "readWrite", db: "devopsdb" }]
    });
