apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-init.js: |
    db.createUser({
      user: 'admin',
      pwd: 'password',
      roles: [{ role: 'readWrite', db: 'devopsdb' }]
    });
