name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust based on your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check frontend Dockerfile existence
        run: |
          ls -l ./frontend/Dockerfile  # Check if the Dockerfile exists in the frontend folder

      - name: Build and push Docker image for frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend  # Frontend directory as the build context
          file: ./frontend/Dockerfile  # Path to Dockerfile for frontend
          push: true
          tags: mukeshsaini7/devops-sample-app-frontend:${{ github.sha }}

      - name: Check backend Dockerfile existence
        run: |
          ls -l ./backend/Dockerfile  # Check if the Dockerfile exists in the backend folder

      - name: Build and push Docker image for backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend  # Backend directory as the build context
          file: ./backend/Dockerfile  # Path to Dockerfile for backend
          push: true
          tags: mukeshsaini7/devops-sample-app-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -sSL -o /usr/local/bin/kubectl https://dl.k8s.io/release/stable.txt
          curl -LO "https://dl.k8s.io/release/$(cat stable.txt)/bin/linux/amd64/kubectl"
          chmod +x /usr/local/bin/kubectl
          kubectl version --client

      - name: Set up EKS Kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name sample-eks-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-manifests/frontend-deployment.yaml
          kubectl apply -f k8s-manifests/frontend-service.yaml
          kubectl apply -f k8s-manifests/backend-deployment.yaml
          kubectl apply -f k8s-manifests/backend-service.yaml
          kubectl apply -f k8s-manifests/mongo-service.yaml
          kubectl apply -f k8s-manifests/mongo-pvc.yaml
          kubectl apply -f k8s-manifests/mongo-statefulset.yaml
          kubectl rollout status deployment/devops-sample-app-frontend --timeout=300s
          kubectl rollout status deployment/devops-sample-app-backend --timeout=300s
